### ISSUE TITLE
感谢您的分享，我在p20，p30上运行源码，提示初始化相机失败

### ISSUE THREAD

**Issue by wangchang163** [KnightAndroid/Camera1Java#1]

**Comment by wangchang163** [comment]
2019-11-01 17:02:51.972 1926-1926/com.knight.cameraone W/System.err: java.lang.RuntimeException: setParameters failed
2019-11-01 17:02:51.972 1926-1926/com.knight.cameraone W/System.err:     at android.hardware.Camera.native_setParameters(Native Method)
2019-11-01 17:02:51.972 1926-1926/com.knight.cameraone W/System.err:     at android.hardware.Camera.setParameters(Camera.java:2174)
2019-11-01 17:02:51.972 1926-1926/com.knight.cameraone W/System.err:     at com.knight.cameraone.CameraPresenter.initParameters(CameraPresenter.java:255)
2019-11-01 17:02:51.972 1926-1926/com.knight.cameraone W/System.err:     at com.knight.cameraone.CameraPresenter.openCamera(CameraPresenter.java:216)
2019-11-01 17:02:51.972 1926-1926/com.knight.cameraone W/System.err:     at com.knight.cameraone.CameraPresenter.access$400(CameraPresenter.java:40)
2019-11-01 17:02:51.972 1926-1926/com.knight.cameraone W/System.err:     at com.knight.cameraone.CameraPresenter$4.surfaceCreated(CameraPresenter.java:181)

**Comment by wangchang163** [comment]
最后发现并不是由于设置预览尺寸引起的，而是由于设置 mParameters.setExposureCompensation(5);引起的，注释掉这个就行了

**Comment by wying111** [comment]
@wangchang163 我注释掉虽然能跑了，但拍照还是报错，相机开发真的好多坑啊

**Comment by wangchang163** [comment]
> @wangchang163 我注释掉虽然能跑了，但拍照还是报错，相机开发真的好多坑啊

你查一下，我这边已经上线了，需要注意的是bitmap的处理，回收的bug提示有很多地方会提示溢出

**Comment by KnightAndroid** [comment]
> @wangchang163 我注释掉虽然能跑了，但拍照还是报错，相机开发真的好多坑啊

对呀，部分机型要单独做适配
